"""Generate Codex-compatible adapters for the pinned scientific skill catalog."""

from __future__ import annotations

import json
import shutil
from pathlib import Path, PurePosixPath
from typing import Any


GENERATED_MARKER = "<!-- Generated by scripts/generate_wrappers.py; do not edit. -->"


def _quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _codex_description(value: str) -> str:
    if len(value) <= 1024:
        return value
    shortened = value[:1023].rsplit(" ", 1)[0].rstrip()
    if not shortened:
        shortened = value[:1023]
    return shortened + "…"


def _record(record: dict[str, Any]) -> tuple[str, str, str, list[str], str, str]:
    name = record.get("name")
    description = record.get("description")
    status = record.get("status")
    reasons = record.get("reasons")
    source = record.get("path")
    license_name = record.get("license", "Unknown")
    if not isinstance(name, str) or not name:
        raise ValueError("Skill record has no name")
    if not isinstance(description, str) or not description:
        raise ValueError(f"Skill record {name} has no description")
    if status not in {"active", "inactive"}:
        raise ValueError(f"Skill record {name} has invalid status: {status}")
    if not isinstance(reasons, list) or not all(isinstance(reason, str) for reason in reasons):
        raise ValueError(f"Skill record {name} has invalid reasons")
    if not isinstance(source, str) or not source:
        raise ValueError(f"Skill record {name} has no source path")
    source_path = PurePosixPath(source)
    if source_path.is_absolute() or ".." in source_path.parts:
        raise ValueError(f"Skill record {name} has unsafe source path: {source}")
    return name, description, status, reasons, source_path.as_posix(), str(license_name)


def render_skill_wrapper(record: dict[str, Any]) -> str:
    name, description, status, reasons, source, license_name = _record(record)
    title = name.replace("-", " ").title()
    reasons_text = ", ".join(f"`{reason}`" for reason in reasons) if reasons else "none"
    if status == "inactive":
        activation = (
            "Do not read the upstream instructions until the user has seen every audit reason and "
            "given explicit acknowledgement. Acknowledgement permits instruction inspection only."
        )
    else:
        activation = (
            "Read the upstream instructions only after confirming this record is still active in the "
            "current inventory."
        )
    return f"""---
name: {name}
description: {_quoted(_codex_description(description))}
---

{GENERATED_MARKER}

# {title}

Use this Codex adapter for the pinned upstream scientific skill.

## Catalog status

- Status: `{status}`
- Audit reasons: {reasons_text}
- Upstream license: `{license_name}`
- Inventory: `../../inventory.json`
- Upstream instructions: `../../../{source}/SKILL.md`

## Procedure

1. Resolve the plugin root as three directories above this skill directory.
2. Read the matching inventory record and verify its status, reasons, source path, and pinned revision.
3. {activation}
4. Treat upstream frontmatter as source metadata, not as Codex configuration. Follow the instruction body only where it is compatible with available Codex tools and the current user-approved plan.
5. Treat tools named for another agent runtime as capability requests. Map them to an available Codex tool only when the behavior is equivalent; otherwise report the unavailable capability.
6. Ask before credentials, package installation, new network hosts, remote compute, writes, paid services, destructive actions, or imported executable code.
7. Use `$science-provenance` for produced scientific outputs and `$science-review` before presenting scientific claims.

## Boundaries

- This wrapper does not grant credentials, network access, package installation, or script execution.
- Do not change an inactive record to active from inside a research task.
- Preserve failures, uncertainty, source identifiers, and licensing constraints.
"""


def render_agent_manifest(record: dict[str, Any]) -> str:
    name, _, _, _, _, _ = _record(record)
    display_name = name.replace("-", " ").title()
    short_description = f"Use the audited {name} scientific workflow"
    if len(short_description) > 64:
        short_description = f"Audited scientific workflow for {name}"[:64].rstrip()
    default_prompt = f"Use ${name} for this scientific task with catalog safeguards."
    return f"""interface:
  display_name: {_quoted(display_name)}
  short_description: {_quoted(short_description)}
  default_prompt: {_quoted(default_prompt)}
policy:
  allow_implicit_invocation: false
"""


def _records(inventory: dict[str, Any]) -> list[dict[str, Any]]:
    records = inventory.get("skills")
    if not isinstance(records, list):
        raise ValueError("Inventory has no skills list")
    names: set[str] = set()
    ordered: list[dict[str, Any]] = []
    for raw_record in records:
        if not isinstance(raw_record, dict):
            raise ValueError("Inventory contains a non-object skill record")
        name, *_ = _record(raw_record)
        if name in names:
            raise ValueError(f"Inventory contains duplicate skill: {name}")
        names.add(name)
        ordered.append(raw_record)
    return sorted(ordered, key=lambda item: str(item["name"]))


def check_sources(inventory: dict[str, Any], plugin_root: Path) -> list[str]:
    errors: list[str] = []
    for record in _records(inventory):
        name, _, _, _, source, _ = _record(record)
        if not (plugin_root / source / "SKILL.md").is_file():
            errors.append(f"{name}: upstream SKILL.md is missing at {source}")
    return errors


def check_wrappers(inventory: dict[str, Any], output_root: Path) -> list[str]:
    errors: list[str] = []
    expected_names: set[str] = set()
    for record in _records(inventory):
        name, *_ = _record(record)
        expected_names.add(name)
        expected = {
            "SKILL.md": render_skill_wrapper(record),
            "agents/openai.yaml": render_agent_manifest(record),
        }
        for relative, contents in expected.items():
            path = output_root / name / relative
            if not path.is_file():
                errors.append(f"{name}/{relative} is missing")
            elif path.read_text(encoding="utf-8") != contents:
                errors.append(f"{name}/{relative} is stale")
    if output_root.is_dir():
        for skill_dir in output_root.iterdir():
            skill_file = skill_dir / "SKILL.md"
            if (
                skill_dir.is_dir()
                and skill_dir.name not in expected_names
                and skill_file.is_file()
                and GENERATED_MARKER in skill_file.read_text(encoding="utf-8", errors="replace")
            ):
                errors.append(f"{skill_dir.name}/ is a stale generated wrapper")
    return errors


def generate_wrappers(inventory: dict[str, Any], output_root: Path) -> dict[str, int]:
    records = _records(inventory)
    expected_names = {str(record["name"]) for record in records}
    output_root.mkdir(parents=True, exist_ok=True)
    for record in records:
        name, *_ = _record(record)
        skill_dir = output_root / name
        skill_file = skill_dir / "SKILL.md"
        if skill_file.is_file() and GENERATED_MARKER not in skill_file.read_text(
            encoding="utf-8", errors="replace"
        ):
            raise FileExistsError(f"Refusing to overwrite non-generated skill: {skill_dir}")
        (skill_dir / "agents").mkdir(parents=True, exist_ok=True)
        skill_file.write_text(render_skill_wrapper(record), encoding="utf-8")
        (skill_dir / "agents" / "openai.yaml").write_text(
            render_agent_manifest(record), encoding="utf-8"
        )
    for skill_dir in output_root.iterdir():
        skill_file = skill_dir / "SKILL.md"
        if (
            skill_dir.is_dir()
            and skill_dir.name not in expected_names
            and skill_file.is_file()
            and GENERATED_MARKER in skill_file.read_text(encoding="utf-8", errors="replace")
        ):
            shutil.rmtree(skill_dir)
    return {
        "generated": len(records),
        "active": sum(record["status"] == "active" for record in records),
        "inactive": sum(record["status"] == "inactive" for record in records),
    }
